@baseUrl = http://localhost:3001
@authToken = {{authenticate.response.body.accessToken}}

# USER

### Cria um usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "momo",
  "email": "momo@gmail.com",
  "profilePicture": "fakefot.com",
  "password": "Ab?123456"
}

### Pega todos os usuarios

GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}

### Pega o usuario pelo id
GET {{baseUrl}}/users/5
Authorization: Bearer {{authToken}}

### Salva Post para o Usuario
POST {{baseUrl}}/users/saved-posts/25
Authorization: Bearer {{authToken}}

### Remove um Post do salvos do usuario 
DELETE {{baseUrl}}/users/saved-posts/10
Authorization: Bearer {{authToken}}

### Pega todos os posts salvos do usuario
GET {{baseUrl}}/users/saved-posts
Authorization: Bearer {{authToken}}

### Upload Profile Picture
POST {{baseUrl}}/users/upload-profile
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="halibel.jpg"
Content-Type: image/jpeg

< ./dev/images/halibel.jpg
------WebKitFormBoundary--

### Get Profile Picture
GET {{baseUrl}}/users/profile/user-profile-1737894734379-329321805.jpg


### Get the blogger post
GET {{baseUrl}}/users/blogger/posts
Authorization: Bearer {{authToken}}

# POST

### Cria um post
POST {{baseUrl}}/posts/create
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "title": "The Rise of Remote Work: A Permanent Transformation2",
    "content": "What began as a necessity during lockdowns has evolved into a fundamental reimagining of workplace dynamics. This article delves into how remote and hybrid work models are reshaping employment, productivity, and work-life balance across industries.",
    "coverImage": "https://example.com/images/remote-work.jpg",
    "category": "technology"
  }


### Pega um post por id
GET {{baseUrl}}/posts/17

### Pega post com uma paginação basica
GET {{baseUrl}}/posts?page=1&limit=4&search=Intel

### Pega os post com uma paginação avançada
GET {{baseUrl}}/posts?page=1&limit=10&category=health&search=Sustainable

### Pega recomendação de posts com base no enviado
GET {{baseUrl}}/posts/21/recommendations

### Upload Post Cover Image
POST {{baseUrl}}/posts/upload-cover/8
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="quantun.jpg"
Content-Type: image/jpeg

< ./dev/images/quantun.jpg
------WebKitFormBoundary--

### Get Post Cover Image
GET {{baseUrl}}/posts/cover/post-cover-1737898895956-144566741.jpg

### Deleta post

DELETE {{baseUrl}}/posts/14
Authorization: Bearer {{authToken}}

# AUTH
### Loga o usuario
# @name authenticate
POST  {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "orihime@gmail.com",
  "password": "Ab?123456"
}