@baseUrl = http://localhost:3000
@authToken = {{authenticate.response.body.token}}

# USER

### Cria um usuario
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "name": "rukia",
  "email": "rukia@gmail.com",
  "profilePicture": "fakefot.com",
  "password": "Ab?123456"
}

### Pega todos os usuarios

GET {{baseUrl}}/users

### Pega o usuario pelo id
GET {{baseUrl}}/users/1

### Salva Post para o Usuario
POST {{baseUrl}}/users/4/saved-posts/2

### Remove um Post do salvos do usuario
DELETE {{baseUrl}}/users/4/saved-posts/2

### Pega todos os posts salvos do usuario
GET {{baseUrl}}/users/4/saved-posts

# POST

### Cria um post
POST {{baseUrl}}/posts/create/1
Content-Type: application/json

{
      "title": "The Rise of Decentralized Finance",
      "content": "Decentralized Finance (DeFi) is reshaping the traditional financial landscape. This analysis explores the fundamental concepts of DeFi, its current applications, and its potential to democratize access to financial services across the globe...",
      "coverImage": "https://example.com/images/defi-rise.jpg",
      "category": "technology"
}


### Pega um post por id
GET {{baseUrl}}/posts/1

### Pega todos os post de um usuario
GET {{baseUrl}}/posts/user/1

### Pega post com uma paginação basica
GET {{baseUrl}}/posts?page=1&limit=2

### Pega os post com uma paginação avançada
GET {{baseUrl}}/posts?page=1&limit=10&category=technology&search=nestjs

# AUTH
### Loga o usuario
# @name authenticate
POST  {{baseUrl}}/auth/
Content-Type: application/json

{
  "email": "rukia@gmail.com",
  "password": "Ab?123456"
}